CREATE TABLE IF NOT EXISTS telegram_pending_balance_inputs (
  chat_id VARCHAR(64) PRIMARY KEY,
  account_id BIGINT NOT NULL,
  asset VARCHAR(16) NOT NULL,
  action VARCHAR(16) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
